baseURL = 'https://boiledpotato.xyz'
title = 'Boiled Potato'
theme = "dark"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
    [languages.en]
        languageName = "English"
        weight = 1
        contentDir = "content/en"
        languageCode = "en-gb"

    [languages.es]
        languageName = "Espa√±ol"
        weight = 2
        contentDir = "content/es"
        languageCode = "es-mx"
